#!/usr/bin/env python3

# https://www.kernel.org/doc/Documentation/ABI/testing/debugfs-driver-qat_telemetry

#
# no need to have VFs for PFs data collection

mount -t debugfs none /sys/kernel/debug || true


