#!/usr/bin/env python3

# https://www.kernel.org/doc/Documentation/ABI/testing/debugfs-driver-qat_telemetry

mount -t debugfs none /sys/kernel/debug || true

/sys/kernel/debug/qat_4xxx_0000:ed:00.0/

