name: qatengine
version: "1.0"
summary: QAT Openssl Provider
description: QAT Openssl Provider
base: core24
confinement: strict
grade: stable
platforms:
    intel:
      build-on: [amd64]
      build-for: [amd64]

apps:
  openssl:
    command: usr/bin/openssl
    plugs:
      - intel-qat
      - process-control
    environment:
      OPENSSL_ENGINES: $SNAP/usr/lib/x86_64-linux-gnu/engines-3
  cpa-sample-code:
    command: usr/bin/cpa_sample_code
    plugs:
      - intel-qat
      - process-control
  dc-dp-sample:
    command: usr/bin/dc_dp_sample
    plugs:
      - intel-qat
      - process-control

parts:
  qat_engine:
    plugin: nil
    stage-packages:
      - openssl
      - qatengine
      - qatlib-examples
